@startuml ComponentDiagram

title ChainBuy - Diagrama de Componentes 
package "Frontend" {
  [WebApp] <<component>>
}

package "Aplicação" {
  [API Principal] <<component>>
}

package "Domínio" {
  [Módulo Pedidos] <<component>>
  [Módulo Produtos] <<component>>
  [Módulo Pagamentos] <<component>>
  [Módulo Autenticação] <<component>>
  [Módulo Blockchain] <<component>>
}

package "Infraestrutura" {
  [Banco de Dados] <<database>>
  [Node Blockchain] <<external>>
  [Gateway Pagamento] <<external>>
  [Transportadora] <<external>>
  [Serviço de Autenticação de Terceiros] <<external>>
}

[WebApp] --> [API Principal] : REST

[API Principal] --> [Módulo Pedidos]
[API Principal] --> [Módulo Produtos]
[API Principal] --> [Módulo Pagamentos]
[API Principal] --> [Módulo Autenticação]
[API Principal] --> [Módulo Blockchain]


[Banco de Dados] ..> [Módulo Pedidos] : Implementa persistência
[Banco de Dados] ..> [Módulo Produtos]
[Banco de Dados] ..> [Módulo Autenticação]
[Gateway Pagamento] ..> [Módulo Pagamentos]
[Node Blockchain] ..> [Módulo Blockchain]
[Transportadora] ..> [Módulo Pedidos]
[Serviço de Autenticação de Terceiros] ..> [Módulo Autenticação]

@enduml
